#!/usr/bin/env python3
"""doc_bridge — manage deterministic-state bridge markers in human-authored docs.

A participating repository's generated operational state lives under `.repo/`. This script
helps human-facing documentation (README.md, CURRENT_STATE.md, AI_ASSISTANT.md, etc.)
reference that canonical source without duplicating it.

Usage:
    python3 tools/doc_bridge.py check <doc-path>        # report-only: bridge present?
    python3 tools/doc_bridge.py fix  <doc-path>         # add bridge if missing
    python3 tools/doc_bridge.py status <doc-path>       # print short summary

The bridge marker is a comment inserted immediately after any YAML frontmatter (or at
the very top of the file if there is no frontmatter), before the first # heading.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

BRIDGE_PATTERN = re.compile(r"<!-- deterministic-state-bridge:\s*(\S+)\s*-->")
# NOTE: this template is embedded into a DIFFERENT repository than SKB (e.g. this
# repository's own README.md). A relative link (`../../projects/registry/...`) can never
# resolve there -- relative links only traverse within the same repository/filesystem, and
# on GitHub.com the participant repo and soobujmiah/skb are unrelated repositories. This was
# a real bug (found 2026-09-26, fixed here) that produced a broken link in every repository
# this bridge was inserted into. Use an absolute GitHub URL instead, which resolves correctly
# regardless of which repository embeds it.
SKB_REGISTRY_BASE_URL = "https://github.com/soobujmiah/skb/blob/main/projects/registry"
BRIDGE_SECTION_TEMPLATE = """\
<!-- deterministic-state-bridge: {project_id} -->

**Machine-generated operational state:** see [`.repo/STATUS.md`](./.repo/STATUS.md) (generated by `tools/repo_knowledge`). For cross-project SKB registry state, see [`{project_id}.json`]({base_url}/{project_id}.json) in the parent SKB repository (`soobujmiah/skb`).
"""


def _extract_frontmatter(text: str) -> tuple[str, str]:
    m = re.match(r"^---\n(.*?)\n---\n?(.*)", text, re.DOTALL)
    if m:
        return m.group(1), m.group(2)
    return "", text


def _has_bridge(text: str) -> bool:
    return bool(BRIDGE_PATTERN.search(text))


def _find_first_heading_offset(body: str) -> int:
    m = re.search(r"^# ", body, re.MULTILINE)
    return m.start() if m else len(body)


def cmd_check(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="doc-bridge check")
    parser.add_argument("--project-id", default=None)
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("path")
    args = parser.parse_args(argv[1:])
    path = Path(args.path).resolve()
    if not path.exists():
        print(f"check: {path} does not exist", file=sys.stderr)
        return 1
    text = path.read_text(encoding="utf-8")
    matches = BRIDGE_PATTERN.findall(text)
    if len(matches) != 1:
        print("FAIL: expected exactly one bridge marker")
        return 1
    if args.project_id and matches[0] != args.project_id:
        print("FAIL: bridge project identity mismatch")
        return 1
    if args.strict:
        # Validate the managed paragraph, not repeated links in human prose.
        paragraph_match = re.match(r"\s*(\*\*Machine-generated operational state:\*\*[^\n]*)",
                                   text[BRIDGE_PATTERN.search(text).end():])
        paragraph = paragraph_match.group(1) if paragraph_match else ""
        if not paragraph:
            print("FAIL: managed bridge paragraph missing")
            return 1
        links = re.findall(r"\]\(([^)]+)\)", paragraph)
        status_links = [link for link in links if link.endswith(".repo/STATUS.md")]
        if len(status_links) != 1 or not (path.parent / status_links[0]).is_file():
            print("FAIL: bridge requires exactly one resolvable local STATUS link")
            return 1
        target = f"{SKB_REGISTRY_BASE_URL}/{matches[0]}.json"
        if links.count(target) != 1:
            print("FAIL: missing/duplicated canonical registry link")
            return 1
    print(f"OK: bridge present (project-id={matches[0]})")
    return 0


def cmd_fix(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="doc-bridge fix")
    parser.add_argument("--project-id", default=None)
    parser.add_argument("path", help="path to the markdown document")
    args = parser.parse_args(argv[1:])
    path = Path(args.path).resolve()
    if not path.exists():
        print(f"fix: {path} does not exist", file=sys.stderr)
        return 1
    text = path.read_text(encoding="utf-8")
    if _has_bridge(text):
        markers = BRIDGE_PATTERN.findall(text)
        if len(markers) != 1 or (args.project_id and markers[0] != args.project_id):
            print("FAIL: refusing to rewrite duplicate/wrong-identity bridge", file=sys.stderr)
            return 1
        marker = BRIDGE_PATTERN.search(text)
        paragraph = re.match(r"\s*(\*\*Machine-generated operational state:\*\*[^\n]*)", text[marker.end():])
        if paragraph is None:
            print("FAIL: bridge paragraph missing; refusing to rewrite human content", file=sys.stderr)
            return 1
        repo_root = next((p for p in [path.parent, *path.parents] if (p / ".repo").is_dir()), path.parent)
        status_link = os.path.relpath(repo_root / ".repo/STATUS.md", path.parent)
        replacement = BRIDGE_SECTION_TEMPLATE.format(project_id=markers[0], base_url=SKB_REGISTRY_BASE_URL).splitlines()[2]
        replacement = replacement.replace("./.repo/STATUS.md", status_link)
        start, end = marker.end() + paragraph.start(1), marker.end() + paragraph.end(1)
        new_text = text[:start] + replacement + text[end:]
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            print(f"repaired: generated bridge paragraph in {path.name}")
        else:
            print(f"skip: bridge already correct in {path.name}")
        return 0
    pm = args.project_id or path.stem
    bridge = BRIDGE_SECTION_TEMPLATE.format(project_id=pm, base_url=SKB_REGISTRY_BASE_URL)
    repo_root = next((p for p in [path.parent, *path.parents] if (p / ".repo").is_dir()), path.parent)
    bridge = bridge.replace("./.repo/STATUS.md", os.path.relpath(repo_root / ".repo/STATUS.md", path.parent))
    fm, body = _extract_frontmatter(text)
    sep = "\n" if fm else ""
    insert_pos = _find_first_heading_offset(body)
    new_body = body[:insert_pos] + bridge + sep + body[insert_pos:]
    # new_body already has the bridge inserted at insert_pos -- do not prepend it again.
    new_text = ("---\n" + fm + "\n---\n" + new_body) if fm else new_body
    path.write_text(new_text, encoding="utf-8")
    print(f"fixed: {path} (project-id={pm})")
    return 0


def cmd_status(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="doc-bridge status")
    parser.add_argument("path", help="path to the markdown document")
    args = parser.parse_args(argv[1:])
    path = Path(args.path).resolve()
    if not path.exists():
        print(f"status: {path} does not exist", file=sys.stderr)
        return 1
    text = path.read_text(encoding="utf-8")
    fm, body = _extract_frontmatter(text)
    full = fm + body if fm else text
    if _has_bridge(full):
        m = BRIDGE_PATTERN.search(full)
        project_id = m.group(1) if m else "unknown"
        heading_off = _find_first_heading_offset(body)
        print(f"bridge present (project-id={project_id})")
        print(f"  insertion point: char {len(fm) + heading_off}")
        print(f"  file size: {len(text.encode('utf-8'))} bytes")
        return 0
    print("no bridge found")
    return 1


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    parser = argparse.ArgumentParser(prog="doc-bridge", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    for name, func in (("check", cmd_check), ("fix", cmd_fix), ("status", cmd_status)):
        p = sub.add_parser(name)
        if name in ("fix", "check"):
            p.add_argument("--project-id", default=None)
        if name == "check":
            p.add_argument("--strict", action="store_true")
        p.add_argument("path", help="path to the markdown document")
        p.set_defaults(func=func)
    args = parser.parse_args(argv)
    return args.func(argv)


if __name__ == "__main__":
    sys.exit(main())
